# Generated by Django 2.0.6 on 2018-06-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180310_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.CharField(default='email@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
