# Generated by Django 2.0.6 on 2018-06-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180613_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=12)),
                ('tipo', models.CharField(max_length=12)),
            ],
        ),
    ]
