# Generated by Django 2.0.6 on 2018-06-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='turmas',
        ),
        migrations.AddField(
            model_name='usuario',
            name='turmas',
            field=models.ManyToManyField(to='api.Turma'),
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
