# Generated by Django 2.0.6 on 2018-06-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180613_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(max_length=3000)),
                ('opcaoA', models.TextField(max_length=3000)),
                ('opcaoB', models.TextField(max_length=3000)),
                ('opcaoC', models.TextField(max_length=3000)),
                ('opcaoD', models.TextField(max_length=3000)),
                ('gabarito', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Turma')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turmas',
            field=models.ManyToManyField(blank=True, default=[], to='api.Turma'),
        ),
        migrations.AddField(
            model_name='questao',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Questionario'),
        ),
    ]
