# Generated by Django 2.0.6 on 2018-06-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180623_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='nome',
            field=models.CharField(default='Exemplo', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questao',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='api.Questionario'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios', to='api.Turma'),
        ),
    ]
