# Generated by Django 2.0.6 on 2018-06-23 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180623_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='gabarito',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
